---
# SSH Connection
ansible_user: "ansible"
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_ssh_pipelining: true

# Security
security_ssh_port: 2222

# UFW
ufw_allowed_ports:
  - "{{ security_ssh_port }}"
