---
postgres_root_user: "noob"
postgres_root_password: "nooblearn2code_postgres_pass"
postgres_port: 5432

# Databases
postgres_databases:
  # GitLab
  - name: "gitlab"
    user: "gitlab"
    password: "gitlab_db_pass"
    
  # EthnoSoul Legacy
  - name: "esl"
    user: "esl"
    password: "esl_db_pass"
  
  # API Community Alert
  - name: "community_alert"
    user: "community_alert"
    password: "community_alert_db_pass"

  # Music Bot
  - name: "music_bot"
    user: "music_bot"
    password: "music_bot_db_pass"